"""Export the DSPy auto-mode monitor to TypeScript for the Pi extension.

    uv run python -m scripts.export_ts            # write pi-extension/src/program.generated.ts
    uv run python -m scripts.export_ts --check    # exit 1 if that file is stale
    uv run python -m scripts.export_ts --golden   # also write pi-extension/test/golden.json from the DSPy cache

The questions come from the same DSPy code path that builds the live request, so the extension sends
exactly what the benchmarked program sends. Policy logic (prechecks, state, composition) is ported by
hand in pi-extension/src; the golden file is how the TypeScript proves it still agrees with Python.
"""

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

from dspy.adapters.decision_state import DecisionState
from dspy.adapters.utils import get_field_description_string

from jev_auto import state
from jev_auto.program import AutoModeMonitor, consent_field, match_field

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "pi-extension" / "src" / "program.generated.ts"
GOLDEN = ROOT / "pi-extension" / "test" / "golden.json"
TUNED = ROOT / "bench" / "results" / "tuned_monitor.json"
COMMIT_PREFIX = "// Source commit: "
# Python-only regex syntax that JavaScript rejects or reads differently. Use re flags instead of inline ones.
NON_PORTABLE = re.compile(r"\(\?P[<=>]|\\[AZ]|\(\?[aiLmsux-]+[:)]")
PATTERNS = {
    "sensitive_path": "SENSITIVE_PATH",
    "encoded_exec": "ENCODED_EXEC",
    "shell_substitution": "SHELL_SUBSTITUTION",
    "destroys_work": "DESTROYS_WORK",
}
EXPORTS = [
    ("PROGRAM_HASH", "string"),
    ("INSTRUCTIONS", "string"),
    ("INPUT_FIELDS", "string"),
    ("QUESTIONS", "Record<string, Question>"),
    ("THRESHOLDS", "Record<string, number>"),
    ("ASK_FLOOR", "number"),
    ("RULES", "readonly RuleInfo[]"),
    ("LIMITS", "Record<string, number>"),
    ("READ_ONLY", "readonly string[]"),
    ("READ_ONLY_GIT", "readonly string[]"),
    ("PATTERNS", "Record<string, Pattern>"),
    ("ENVIRONMENT_DEFAULTS", "Record<string, unknown>"),
]
HEADER = """// Generated by scripts/export_ts.py from the DSPy program in jev_auto/. Do not edit by hand.
// After changing the program: `uv run python -m scripts.export_ts --golden`, then `npm test` in pi-extension/.
{commit_line}
// Program hash: {digest}

export interface Question {{
  instructions: string;
  type: "noul";
  criteria: {{ true: unknown; false: unknown }};
}}

export interface RuleInfo {{
  key: string;
  name: string;
  tier: "hard" | "soft";
  must_name: string | null;
  adversarial: boolean;
  match_field: string;
  consent_field: string | null;
}}

export interface Pattern {{
  source: string;
  flags: string;
}}
"""


def load_monitor():
    monitor = AutoModeMonitor()
    if TUNED.exists():
        monitor.load(str(TUNED))
    return monitor


def decision_state(monitor):
    return DecisionState(monitor.judge.signature, monitor.judge.fields, system_one=True)


def pattern(p: re.Pattern) -> dict:
    if NON_PORTABLE.search(p.pattern):
        raise SystemExit(f"non-portable regex for JavaScript: {p.pattern!r}")
    if p.flags & ~(re.IGNORECASE | re.UNICODE):
        raise SystemExit(f"non-portable regex flags for JavaScript: {p.pattern!r}")
    return {"source": p.pattern, "flags": "i" if p.flags & re.IGNORECASE else ""}


def program(monitor) -> dict:
    sig = monitor.judge.signature
    decisions = decision_state(monitor)
    questions = {name: decisions._question(name, sig.output_fields[name], kind) for name, kind in decisions.types.items()}
    rules = []
    for r in monitor.rules:
        if r.tier == "soft" and not r.adversarial and not r.must_name:
            raise SystemExit(f"soft rule {r.key} has no must_name")
        rules.append({
            "key": r.key, "name": r.name, "tier": r.tier, "must_name": r.must_name, "adversarial": r.adversarial,
            "match_field": match_field(r), "consent_field": consent_field(r) if r.tier == "soft" else None,
        })
    environment = state.default_environment("/", user="-", remotes=[])
    environment["user"] = None  # filled per machine by the extension
    environment["trusted_repo"] = None  # filled per session by the extension
    return {
        "INSTRUCTIONS": sig.instructions,
        "INPUT_FIELDS": get_field_description_string(sig.input_fields),
        "QUESTIONS": questions,
        "THRESHOLDS": {name: decisions.fields[name]["threshold"] for name in decisions.types},
        "ASK_FLOOR": monitor.ask_floor,
        "RULES": rules,
        "LIMITS": {
            "maxText": state.MAX_TEXT, "maxFile": state.MAX_FILE, "maxTranscript": state.MAX_TRANSCRIPT,
            "maxToolInput": state.MAX_TOOL_INPUT, "userTurnsFirst": state.USER_TURNS_FIRST, "userTurnsLast": state.USER_TURNS_LAST,
        },
        "READ_ONLY": sorted(state.READ_ONLY),
        "READ_ONLY_GIT": sorted(state.READ_ONLY_GIT),
        "PATTERNS": {name: pattern(getattr(state, const)) for name, const in PATTERNS.items()},
        "ENVIRONMENT_DEFAULTS": environment,
    }


def digest(p: dict) -> str:
    return hashlib.sha256(json.dumps(p, sort_keys=True).encode()).hexdigest()[:12]


def source_commit() -> str:
    def git(*args):
        return subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True).stdout.strip()

    commit = git("rev-parse", "--short", "HEAD") or "unknown"
    return commit + ("-dirty" if git("status", "--porcelain", "jev_auto") else "")


def render(p: dict) -> str:
    values = {"PROGRAM_HASH": digest(p), **p}
    parts = [HEADER.format(commit_line=COMMIT_PREFIX + source_commit(), digest=values["PROGRAM_HASH"])]
    for name, annotation in EXPORTS:
        parts.append(f"export const {name}: {annotation} = {json.dumps(values[name], indent=2, ensure_ascii=False)};\n")
    return "\n".join(parts)


def without_commit(text: str) -> str:
    return "\n".join(line for line in text.splitlines() if not line.startswith(COMMIT_PREFIX))


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if the generated file is stale")
    parser.add_argument("--golden", action="store_true", help="also write the parity vectors from the DSPy cache")
    args = parser.parse_args(argv)

    monitor = load_monitor()
    p = program(monitor)
    text = render(p)
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if without_commit(current) != without_commit(text):
            print(f"{OUT.relative_to(ROOT)} is stale; run `uv run python -m scripts.export_ts --golden`", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(p['QUESTIONS'])} questions, hash {digest(p)})")
    if args.golden:
        from scripts.golden import write_golden

        write_golden(monitor, digest(p), GOLDEN)
    return 0


if __name__ == "__main__":
    sys.exit(main())
